apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: PGDATA
              value: "/var/lib/postgresql/data"
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  labels:
    app: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
        - name: indexer
          image: gcr.io/valora-inc/indexer:latest
          envFrom:
            - configMapRef:
                name: indexer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indexer
data:
  ENVIRONMENT: 'alfajores'
  PORT: '80'
  POLLING_INTERVAL: '1000'
  WEB3_PROVIDER_URL: 'https://alfajores-forno.celo-testnet.org'
  DB_TYPE: 'postgres'
  DB_HOST: 'postgres'
  DB_USERNAME: 'postgres'
  DB_PASSWORD: 'postgres'
  DB_DATABASE: 'postgres'
