name: Workflow

on:
  # Run on pushes to main..
  push:
    branches:
      - cd0
  # ..and any pull request.
  pull_request:

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: yarn
      - run: yarn build
      - run: yarn test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: yarn
      - run: yarn lint
  deploy-alfajores:
    name: Deploy alfajores
    if: github.ref == 'refs/heads/cd0'
    needs:
      - unit
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.ALFAJORES_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Deploy App
        run: ./deploy.sh -n alfajores
